version: 2.1
jobs:
  build:
    working_directory: ~/rocky/python2-trepan
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: cimg/python:2.7.18
      auth:
        username: rockyb
        password: $DOCKERHUB_PASSWORD
    steps:
      - checkout  # checkout source code to working directory
      - run: pip install -e .
      - run: pip install -r requirements-dev.txt
      - run: python ./setup.py develop && make test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
