version: 2
jobs:
  build:
    working_directory: ~/rocky/python2-trepan
    docker:
    - image: circleci/python:2.7.16
    steps:
      - checkout  # checkout source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
            pip install -e .
            pip install -r requirements-dev.txt
      - run: python ./setup.py develop && make test-unit test-functional
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
